version: '3.8'

services:
  express-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/srv # Serve the Vite build output
      - ./Caddyfile:/etc/caddy/Caddyfile:ro # Custom Caddy configuration file
